// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJFZEiqrWvMANF5NyCYji_a5d2RepcvLY',
    appId: '1:127168271990:web:2842f0b5b21a2e2593f157',
    messagingSenderId: '127168271990',
    projectId: 'ecorutas-f203f',
    authDomain: 'ecorutas-f203f.firebaseapp.com',
    storageBucket: 'ecorutas-f203f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO6dd1trpXXZ3Iuz-q-hqtyUxuhYi35Wg',
    appId: '1:127168271990:android:6681bc7b37978c9f93f157',
    messagingSenderId: '127168271990',
    projectId: 'ecorutas-f203f',
    storageBucket: 'ecorutas-f203f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDllYxkMrTHV0KMiwuma5X4u2EhloqSGbY',
    appId: '1:127168271990:ios:aaae83be1bd90e6693f157',
    messagingSenderId: '127168271990',
    projectId: 'ecorutas-f203f',
    storageBucket: 'ecorutas-f203f.firebasestorage.app',
    iosBundleId: 'com.example.ecorutas',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDllYxkMrTHV0KMiwuma5X4u2EhloqSGbY',
    appId: '1:127168271990:ios:aaae83be1bd90e6693f157',
    messagingSenderId: '127168271990',
    projectId: 'ecorutas-f203f',
    storageBucket: 'ecorutas-f203f.firebasestorage.app',
    iosBundleId: 'com.example.ecorutas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJFZEiqrWvMANF5NyCYji_a5d2RepcvLY',
    appId: '1:127168271990:web:0392a8c04683184f93f157',
    messagingSenderId: '127168271990',
    projectId: 'ecorutas-f203f',
    authDomain: 'ecorutas-f203f.firebaseapp.com',
    storageBucket: 'ecorutas-f203f.firebasestorage.app',
  );
}
